### ISSUE TITLE
建议记住上次输入的url配置地址

### ISSUE THREAD

**Issue by s7lx** [Potatso/Board#1]
建议记住上次输入的url配置地址。很多人都是反复导入一个地址，而这个地址对应的文件在反复修改

**Comment by iCodesign** [comment]
> 建议记住上次输入的url配置地址
我不认为这是个强需求，所以不会支持。

> 很多人都是反复导入一个地址，而这个地址对应的文件在反复修改
这个会考虑以一种更加优雅的方式去实现，如订阅某个地址。
