### ISSUE TITLE
支持更多的 ss 加密方式

### ISSUE THREAD

**Issue by kxjhlele** [Potatso/Board#21]
chacha20。-ietf。....

**Comment by iCodesign** [comment]
chacha 20 不是支持吗

**Comment by kxjhlele** [comment]
chacha20-ietf 还有几个不支持

**Comment by iCodesign** [comment]
加密方式我参照的是 Shadowsocks for Mac，暂时不打算支持更多的加密方式，意义不是特别大，建议你修改加密方式

**Comment by kxjhlele** [comment]
thx 以为参考 shadowsocks-libev 呢
